### ISSUE TITLE
An uploaded picture with x-sendfile in a stream post results in a placeholder (v0.20 beta 1)

### ISSUE THREAD

**Issue by demux79** [humhub/humhub#1192]
Note: Image handling works well if x-sendfile is disabled.

Installed x-sendfile mod for apache
Enabled  x-sendfile in file options
Uploaded a picture in a stream post
--> stream shows only a placeholder for the image with this error message in the log:
exception 'yii\web\ForbiddenHttpException' with message 'You are not allowed to perform this action.' in /var/www/html/humhub/protected/humhub/components/behaviors/AccessControl.php:74 Stack trace: #0 /var/www/html/humhub/protected/humhub/components/behaviors/AccessControl.php(60): humhub\components\behaviors\AccessControl->forbidden() #1 /var/www/html/humhub/protected/vendor/yiisoft/yii2/base/ActionFilter.php(71): humhub\components\behaviors\AccessControl->beforeAction(Object(yii\base\InlineAction)) #2 [internal function]: yii\base\ActionFilter->beforeFilter(Object(yii\base\ActionEvent)) #3 /var/www/html/humhub/protected/vendor/yiisoft/yii2/base/Component.php(541): call_user_func(Array, Object(yii\base\ActionEvent)) #4 /var/www/html/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(263): yii\base\Component->trigger('beforeAction', Object(yii\base\ActionEvent)) #5 /var/www/html/humhub/protected/vendor/yiisoft/yii2/web/Controller.php(108): yii\base\Controller->beforeAction(Object(yii\base\InlineAction)) #6 /var/www/html/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(149): yii\web\Controller->beforeAction(Object(yii\base\InlineAction)) #7 /var/www/html/humhub/protected/vendor/yiisoft/yii2/base/Module.php(455): yii\base\Controller->runAction('', Array) #8 /var/www/html/humhub/protected/vendor/yiisoft/yii2/web/Application.php(84): yii\base\Module->runAction('admin', Array) #9 /var/www/html/humhub/protected/vendor/yiisoft/yii2/base/Application.php(375): yii\web\Application->handleRequest(Object(humhub\components\Request)) #10 /var/www/html/humhub/index.php(25): yii\base\Application->run() #11 {main}

**Comment by luke-** [comment]
Alrady fixed in master: https://github.com/humhub/humhub/commit/b378bd9113d16688b4e91ded8d0c197e49c00816

**Comment by demux79** [comment]
Issue remains for me. Placeholder when x-sendfile is enabled. When I disable x-sendfile I can see the picture.

**Comment by luke-** [comment]
Does this affects all post images?

**Comment by demux79** [comment]
Yes. All images. Other file formats work fine.

**Comment by luke-** [comment]
Maybe it's an webserver configuration issue?

We're using also XSendfile on our community site

**Comment by demux79** [comment]
Maybe. Do you have any suggestion what to look at?

**Comment by demux79** [comment]
Works after adding
XSendFile On
XSendFilePath /path/to/humhub/uploads
to apache2.conf
see https://www.humhub.org/docs/guide-admin-adv-xsendfile.html
