### ISSUE TITLE
LDAP login problems after update from 1.0.0 beta1 to beta3

### ISSUE THREAD

**Issue by evolun** [humhub/humhub#1427]
I have updated humhub installation (git/composer based) from 1.0.0 beta 1 to 1.0.0 beta 3 and now LDAP users can't login, only "incorrect username or password" message is swown at login, no exception or log message.

I 'm in debug mode and from authentication LDAP, in administration, the status result is ok fetching correctly the users.

How I can debug this?

**Comment by luke-** [comment]
This was a problem in current git master which is fixed now.

**Comment by chaoticreality** [comment]
Hi @luke-, I'm still experiencing this issue with the latest code, any tips for the best way to debug? Ta, M
