### ISSUE TITLE
Custom oEmbeds don't work

### ISSUE THREAD

**Issue by binarynos** [humhub/humhub#2126]
I tried to add some custom oEmbed providers but the none of them work. I don't see any errors in browser console or the server side. Here are my settings:
Url Prefix 
twitter.com
Endpoint Url 
https://publish.twitter.com/oembed?url=%url%
Url Prefix 
facebook.com
Endpoint Url 
https://www.facebook.com/plugins/post/oembed.json/?url=%url%
Url Prefix 
instagram.com
Endpoint Url 
https://api.instagram.com/oembed?url=%url%
What is going wrong? Any suggestions? Thanks

**Comment by binarynos** [comment]
Okay, it works, there was a problem with curl

**Comment by Felli** [comment]
I got Twitter working fine, tho Facebook & Instagram would be a slightly harder...

**Comment by binarynos** [comment]
@Felli  can you share the settings or any other changes you did to get it working?

**Comment by Felli** [comment]
Sure, I basically did the same as above with Twitter & Instagram, tho Facebook is a little tricky and I'm still working on this one...
### Url Prefix
twitter.com
### Endpoint Url
https://publish.twitter.com/oembed?url=%url%&format=json

As for Instagram
### Url Prefix
instagram.com
### Endpoint
https://api.instagram.com/oembed?url=%url%&format=json

If these don't work on your installation you should check your logs from your admin panel on your site. :+1:

**Comment by binarynos** [comment]
Still doesn't work. The log has 16  entries. Most are info entries and some errors:
`Could not connect to HumHub API! Error in cURL request: Could not resolve host: api.humhub.com`
This went away after  increased the cURL timeout.
Should i share the info entries too?

**Comment by binarynos** [comment]
Well I got it working adding &format=json does the work. 
Thanks

**Comment by Felli** [comment]
As for Facebook, this one is the more tricky one as the oembed doesn't work in the way Humhub is made for example would be the difference between Facebook's and Twitter's.

**Comment by binarynos** [comment]
Okay but i still don't know what was going wrong because even if you don't add &format=json the URLs return json

**Comment by gigabytedevelopers** [comment]
Could you send a screenshot showing that yours is working? I've tried mine,
and it still doesn't work.

**Comment by Felli** [comment]
Here's a screenshot from me.
![](http://image.prntscr.com/image/c92b13ae63ca4cf09bd4dec87abed149.png)

**Comment by gigabytedevelopers** [comment]
@Felli, @binarynos .. This is awesome! I just wonder why mine is not working! Could you please give a step by step procedure on how to go about this in order to make it functional on mine? 
I appreciate!

**Comment by Felli** [comment]
@gigabytedevelopers 

> ### Url Prefix
> twitter.com
> ### Endpoint Url
> https://publish.twitter.com/oembed?url=%url%&format=json
>
> As for Instagram
> ### Url Prefix
> instagram.com
> ### Endpoint
> https://api.instagram.com/oembed?url=%url%&format=json

This is all I did.

**Comment by gigabytedevelopers** [comment]
@Felli , where exactly did you add this? Is it through the admin section of humhub? If it is, then I am doing it right but mine still doesn't work, what exactly am I doing wrong? or is there a file you had to edit manually to acheive this?

**Comment by gigabytedevelopers** [comment]
![screenshot 6](https://cloud.githubusercontent.com/assets/19718407/21582758/6645cd90-d065-11e6-87d6-59b4ea214083.png)

What is the difference with what am doing and what you are doing, its obviously the same, yet I can't still get mine to work. How exactly did you test to see if it works? Was it just the URL of the twitter post you copied and pasted into the textarea of humhub before posting it?

**Comment by Felli** [comment]
Hmm... This is questionable because it should be working just by placing that then posting a link like
https://twitter.com/angularjs/status/733366543455637505
Then it should show as the post itself.

**Comment by gigabytedevelopers** [comment]
![capture](https://cloud.githubusercontent.com/assets/19718407/21582981/559c4c56-d06c-11e6-9200-302193db9fd5.PNG)

LOL!! @Felli , this shit just got real, I have tried with your link, still no luck! I really don't know what's wrong!

**Comment by Felli** [comment]
Ok, try deleting `&format=json` and saving, after that try deleting your browser cache and replacing `&format=json`

**Comment by gigabytedevelopers** [comment]
Hmmmmm! Still no luck! Right now, am furious!

**Comment by binarynos** [comment]
Humhub works strangely when it comes to embeds. the settings are the same. Even i had to try a thousand times before it worked. The biggest problem is that when it doesn't work, no errors appear neither on the browser nor at the backend. Maybe humhub Devs can tell you more

**Comment by gigabytedevelopers** [comment]
I hope so, but where they at right now? Huh? 😳

**Comment by Felli** [comment]
@gigabytedevelopers the Devs are busy with the changing of the new year, as well as the actual software, they can't be everywhere at once, at the moment it's a three man team with a community of developers helping out. :smile:

**Comment by gigabytedevelopers** [comment]
Ok @Felli, I hear you. Thanks for the help so far! Will keep trying to see
if mine would work out for me. I appreciate how you have been of assistance
so far!
Thanks!

**Comment by Felli** [comment]
No problem, tho I should get back to work on my actual projects now! :smile:

**Comment by bposlon** [comment]
any updates on this? 

also, is there a plan for embedding imgur images and galleries? maybe even google photos?

**Comment by Felli** [comment]
@bposlon Everything should be working fine, as for Imgur it might be better to create a module for embedding Imgur images and galleries.

**Comment by bposlon** [comment]
Yeah, I agree. Any takers? :) 

Maybe @Felli ?

**Comment by Felli** [comment]
Hmm... I'll take to some members of @GreenVolume to see if we could do something for this, no promises it'll make it through our weird processing system.

**Comment by luke-** [comment]
I've added a wiki page with OEmbed examples for Imgur and Twitter:
https://community.humhub.com/s/installation-and-setup/wiki/page/view?title=OEmbed+provider

**Comment by yotink522** [comment]
hi
