### ISSUE TITLE
Remove FormatterApp

### ISSUE THREAD

**Issue by luke-** [humhub/humhub#5045]
Check usages (core & module) of formatterApp and remove if possible.
+ Add to migration notes docs 

https://github.com/humhub/humhub/blob/master/protected/humhub/config/common.php#L103-L105

**Comment by yurabakhtin** [comment]
@luke- Done in PR https://github.com/humhub/humhub/pull/5048

**Comment by luke-** [comment]
Thanks could you find a usage in modules or somewhere else?

It would also be good to add this in the migration notes of the documentation.

**Comment by yurabakhtin** [comment]
@luke- 

> Thanks could you find a usage in modules or somewhere else?

No. I don't find any string `formatterApp` in external modules.

> It would also be good to add this in the migration notes of the documentation.

If the config `formatterApp` was not used in modules then I think we should not write about this in documentation, right?

**Comment by luke-** [comment]
@yurabakhtin possibly from ThirdParty modules, I would add it to be on the safe side.

**Comment by luke-** [comment]
@yurabakhtin I receive following error on our translation environemnt on `develop` branch.
Any idea?

``` 
translate@web3:~/htdocs$ git pull
Already up to date.
translate@web3:~/htdocs$ cd htdocs^C
translate@web3:~/htdocs$ php protected/yii migrate/up
Exception 'yii\base\InvalidConfigException' with message 'The configuration for the "formatterApp" component must contain a "class" element.'

in /var/www/translate/htdocs/protected/vendor/yiisoft/yii2/di/ServiceLocator.php:209

Stack trace:
#0 /var/www/translate/htdocs/protected/vendor/yiisoft/yii2/di/ServiceLocator.php(265): yii\di\ServiceLocator->set('formatterApp', Array)
#1 /var/www/translate/htdocs/protected/vendor/yiisoft/yii2/base/Component.php(181): yii\di\ServiceLocator->setComponents(Array)
#2 /var/www/translate/htdocs/protected/vendor/yiisoft/yii2/BaseYii.php(558): yii\base\Component->__set('components', Array)
#3 /var/www/translate/htdocs/protected/vendor/yiisoft/yii2/base/BaseObject.php(107): yii\BaseYii::configure(Object(humhub\components\console\Application), Array)
#4 /var/www/translate/htdocs/protected/vendor/yiisoft/yii2/base/Application.php(212): yii\base\BaseObject->__construct(Array)
#5 /var/www/translate/htdocs/protected/vendor/yiisoft/yii2/console/Application.php(90): yii\base\Application->__construct(Array)
#6 /var/www/translate/htdocs/protected/yii(28): yii\console\Application->__construct(Array)
#7 {main}
```

**Comment by yurabakhtin** [comment]
@luke- To fix the bug we should regenerate the config file `protected/config/dynamic.php`, as I understand it is possible only after deleting this file and do new install, but it is not appropriate for upgrade I think, so I have implemented a fix in PR https://github.com/humhub/humhub/pull/5051.

**Comment by luke-** [comment]
@yurabakhtin Thanks looks good. Unfortunately, after merging, I noticed that the problem still occurs with the Console Application.

**Comment by yurabakhtin** [comment]
@luke- Ah yes, I had to do the same fix for console app. Fixed in PR https://github.com/humhub/humhub/pull/5052

**Comment by luke-** [comment]
@yurabakhtin Thanks!
