### ISSUE TITLE
Migration failed at update 1.9

### ISSUE THREAD

**Issue by smitti** [humhub/humhub#5204]
### What steps will reproduce the problem?
Updating to 1.9 after issue #4946 (propably important?)
### What is the expected result?
        Yii Migration Tool (based on Yii v2.0.40)

Total 3 new migrations to be applied:
	m210211_051243_container_tag
	m210331_115144_default_timezone
	m210506_060737_profile_field_directory_filter

*** applying m210211_051243_container_tag
    > create table contentcontainer_tag ...Exception: SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'contentcontainer_tag' already exists
The SQL being executed was: CREATE TABLE `contentcontainer_tag` (
	`id` int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`name` varchar(100) NOT NULL,
	`contentcontainer_class` char(60) NOT NULL
) (/is/htdocs/wp11141389_5VUUJ7N9W6/b-u-p-daheim.de/protected/vendor/yiisoft/yii2/db/Schema.php:678)
#0 /is/htdocs/wp11141389_5VUUJ7N9W6/b-u-p-daheim.de/protected/vendor/yiisoft/yii2/db/Command.php(1304): yii\db\Schema->convertException(Object(PDOException), 'CREATE TABLE `c...')
#1 /is/htdocs/wp11141389_5VUUJ7N9W6/b-u-p-daheim.de/protected/vendor/yiisoft/yii2/db/Command.php(1099): yii\db\Command->internalExecute('CREATE TABLE `c...')
#2 /is/htdocs/wp11141389_5VUUJ7N9W6/b-u-p-daheim.de/protected/vendor/yiisoft/yii2/db/Migration.php(323): yii\db\Command->execute()
#3 /is/htdocs/wp11141389_5VUUJ7N9W6/b-u-p-daheim.de/protected/humhub/modules/content/migrations/m210211_051243_container_tag.php(23): yii\db\Migration->createTable('contentcontaine...', Array)
#4 /is/htdocs/wp11141389_5VUUJ7N9W6/b-u-p-daheim.de/protected/vendor/yiisoft/yii2/db/Migration.php(114): m210211_051243_container_tag->safeUp()
#5 /is/htdocs/wp11141389_5VUUJ7N9W6/b-u-p-daheim.de/protected/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(744): yii\db\Migration->up()
#6 /is/htdocs/wp11141389_5VUUJ7N9W6/b-u-p-daheim.de/protected/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(202): yii\console\controllers\BaseMigrateController->migrateUp('m210211_051243_...')
#7 [internal function]: yii\console\controllers\BaseMigrateController->actionUp(0)
#8 /is/htdocs/wp11141389_5VUUJ7N9W6/b-u-p-daheim.de/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#9 /is/htdocs/wp11141389_5VUUJ7N9W6/b-u-p-daheim.de/protected/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams(Array)
#10 /is/htdocs/wp11141389_5VUUJ7N9W6/b-u-p-daheim.de/protected/vendor/yiisoft/yii2/console/Controller.php(184): yii\base\Controller->runAction('up', Array)
#11 /is/htdocs/wp11141389_5VUUJ7N9W6/b-u-p-daheim.de/protected/humhub/commands/MigrateController.php(198): yii\console\Controller->runAction('up')
#12 /is/htdocs/wp11141389_5VUUJ7N9W6/b-u-p-daheim.de/protected/humhub/modules/admin/controllers/InformationController.php(95): humhub\commands\MigrateController::webMigrateAll()
#13 [internal function]: humhub\modules\admin\controllers\InformationController->actionDatabase()
#14 /is/htdocs/wp11141389_5VUUJ7N9W6/b-u-p-daheim.de/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#15 /is/htdocs/wp11141389_5VUUJ7N9W6/b-u-p-daheim.de/protected/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams(Array)
#16 /is/htdocs/wp11141389_5VUUJ7N9W6/b-u-p-daheim.de/protected/vendor/yiisoft/yii2/base/Module.php(534): yii\base\Controller->runAction('database', Array)
#17 /is/htdocs/wp11141389_5VUUJ7N9W6/b-u-p-daheim.de/protected/vendor/yiisoft/yii2/web/Application.php(104): yii\base\Module->runAction('admin/informati...', Array)
#18 /is/htdocs/wp11141389_5VUUJ7N9W6/b-u-p-daheim.de/protected/vendor/yiisoft/yii2/base/Application.php(392): yii\web\Application->handleRequest(Object(humhub\components\Request))
#19 /is/htdocs/wp11141389_5VUUJ7N9W6/b-u-p-daheim.de/index.php(25): yii\base\Application->run()
#20 {main}
*** failed to apply m210211_051243_container_tag (time: 0.001s)

0 from 3 migrations were applied.

Migration failed. The rest of the migrations are canceled.
    
### What do you get instead?
The section People won´t work, an error is shown
### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.9
| PHP version      | 7.4
| Operating system |

**Comment by luke-** [comment]
There must have been a previous error during the migration.

Can you take a look at the `protected/runtime/logs/app.log` file?

**Comment by smitti** [comment]
Yes of course:
[app.log](https://github.com/humhub/humhub/files/6888440/app.log)

**Comment by luke-** [comment]
@smitti Can you please check that all tables are using the same table engine (InnoDB) and the charset `utf8mb4_unicode_ci`.
You can do this with PHPMyAdmin/Adminer for example.

Then please try to delete the tables:
- contentcontainer_tag
- contentcontainer_tag_relation

And try the migration again.

**Comment by luke-** [comment]
@yurabakhtin Can you please take a look here?

**Comment by Bust3r666** [comment]
I have the same problem and i have try to delete:
    contentcontainer_tag
    contentcontainer_tag_relation

The problem isn't fixed yet, the table engine are all (InnoDB) with the charset utf8mb4_unicode_ci.

**Comment by luke-** [comment]
@Bust3r666 Then what do you get for an error?

**Comment by Bust3r666** [comment]
```

Total 3 new migrations to be applied:
	m210211_051243_container_tag
	m210331_115144_default_timezone
	m210506_060737_profile_field_directory_filter

*** applying m210211_051243_container_tag
    > create table contentcontainer_tag ... done (time: 0.006s)
    > create unique index unique-contentcontainer-tag on contentcontainer_tag (contentcontainer_class,name) ... done (time: 0.005s)
    > create table contentcontainer_tag_relation ... done (time: 0.008s)
    > add primary key pk-contentcontainer-tag-rel on contentcontainer_tag_relation (contentcontainer_id,tag_id) ... done (time: 0.010s)
    > add foreign key fk-contentcontainer-tag-rel-contentcontainer-id: contentcontainer_tag_relation (contentcontainer_id) references contentcontainer (id) ... done (time: 0.017s)
    > add foreign key fk-contentcontainer-tag-rel-tag-id: contentcontainer_tag_relation (tag_id) references contentcontainer_tag (id) ... done (time: 0.016s)
    > add column tags_cached string NULL DEFAULT NULL to table contentcontainer ...Exception: SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'tags_cached'
The SQL being executed was: ALTER TABLE `contentcontainer` ADD `tags_cached` varchar(255) NULL DEFAULT NULL (/var/www/humhub/protected/vendor/yiisoft/yii2/db/Schema.php:678)
#0 /var/www/humhub/protected/vendor/yiisoft/yii2/db/Command.php(1304): yii\db\Schema->convertException(Object(PDOException), 'ALTER TABLE `co...')
#1 /var/www/humhub/protected/vendor/yiisoft/yii2/db/Command.php(1099): yii\db\Command->internalExecute('ALTER TABLE `co...')
#2 /var/www/humhub/protected/vendor/yiisoft/yii2/db/Migration.php(377): yii\db\Command->execute()
#3 /var/www/humhub/protected/humhub/modules/content/migrations/m210211_051243_container_tag.php(35): yii\db\Migration->addColumn('contentcontaine...', 'tags_cached', Object(yii\db\mysql\ColumnSchemaBuilder))
#4 /var/www/humhub/protected/vendor/yiisoft/yii2/db/Migration.php(114): m210211_051243_container_tag->safeUp()
#5 /var/www/humhub/protected/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(744): yii\db\Migration->up()
#6 /var/www/humhub/protected/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(202): yii\console\controllers\BaseMigrateController->migrateUp('m210211_051243_...')
#7 [internal function]: yii\console\controllers\BaseMigrateController->actionUp(0)
#8 /var/www/humhub/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#9 /var/www/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams(Array)
#10 /var/www/humhub/protected/vendor/yiisoft/yii2/console/Controller.php(184): yii\base\Controller->runAction('up', Array)
#11 /var/www/humhub/protected/humhub/commands/MigrateController.php(198): yii\console\Controller->runAction('up')
#12 /var/www/humhub/protected/humhub/modules/admin/controllers/InformationController.php(95): humhub\commands\MigrateController::webMigrateAll()
#13 [internal function]: humhub\modules\admin\controllers\InformationController->actionDatabase()
#14 /var/www/humhub/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#15 /var/www/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams(Array)
#16 /var/www/humhub/protected/vendor/yiisoft/yii2/base/Module.php(534): yii\base\Controller->runAction('database', Array)
#17 /var/www/humhub/protected/vendor/yiisoft/yii2/web/Application.php(104): yii\base\Module->runAction('admin/informati...', Array)
#18 /var/www/humhub/protected/vendor/yiisoft/yii2/base/Application.php(392): yii\web\Application->handleRequest(Object(humhub\components\Request))
#19 /var/www/humhub/index.php(25): yii\base\Application->run()
#20 {main}
*** failed to apply m210211_051243_container_tag (time: 0.063s)


0 from 3 migrations were applied.

Migration failed. The rest of the migrations are canceled.

```


I try to remove 'tags_cached' too?

**Comment by ArchBlood** [comment]
Sounds like it's related to the 1.8 migration error for those using normal MySQL instead of InnoDB and MariaDB

**Comment by luke-** [comment]
@Bust3r666  Can you please delete:
`contentcontainer_tag` table
`contentcontainer_tag_relation` table
AND
the column "tags_cached" of the `contentcontainer` table. (not whole table!)

And send us the error message again?

**Comment by smitti** [comment]
Thank https://github.com/luke- for support. My problem is solved.

**Comment by Bust3r666** [comment]
Hi,

i have delete:
contentcontainer_tag table
contentcontainer_tag_relation table
AND
the column tags_cached of the contentcontainer table. 

But now give me this error.

`       Yii Migration Tool (based on Yii v2.0.40)

Total 3 new migrations to be applied:
	m210211_051243_container_tag
	m210331_115144_default_timezone
	m210506_060737_profile_field_directory_filter

*** applying m210211_051243_container_tag
    > create table contentcontainer_tag ... done (time: 0.008s)
    > create unique index unique-contentcontainer-tag on contentcontainer_tag (contentcontainer_class,name) ... done (time: 0.007s)
    > create table contentcontainer_tag_relation ... done (time: 0.007s)
    > add primary key pk-contentcontainer-tag-rel on contentcontainer_tag_relation (contentcontainer_id,tag_id) ... done (time: 0.007s)
    > add foreign key fk-contentcontainer-tag-rel-contentcontainer-id: contentcontainer_tag_relation (contentcontainer_id) references contentcontainer (id) ... done (time: 0.020s)
    > add foreign key fk-contentcontainer-tag-rel-tag-id: contentcontainer_tag_relation (tag_id) references contentcontainer_tag (id) ... done (time: 0.026s)
    > add column tags_cached string NULL DEFAULT NULL to table contentcontainer ... done (time: 0.006s)
Exception: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'tags' in 'where clause'
The SQL being executed was: SELECT * FROM `space` WHERE (`tags` != '') AND (`tags` IS NOT NULL) (/var/www/humhub/protected/vendor/yiisoft/yii2/db/Schema.php:678)
#0 /var/www/humhub/protected/vendor/yiisoft/yii2/db/Command.php(1304): yii\db\Schema->convertException(Object(PDOException), 'SELECT * FROM `...')
#1 /var/www/humhub/protected/vendor/yiisoft/yii2/db/Command.php(1165): yii\db\Command->internalExecute('SELECT * FROM `...')
#2 /var/www/humhub/protected/vendor/yiisoft/yii2/db/Command.php(407): yii\db\Command->queryInternal('fetchAll', NULL)
#3 /var/www/humhub/protected/vendor/yiisoft/yii2/db/Query.php(248): yii\db\Command->queryAll()
#4 /var/www/humhub/protected/vendor/yiisoft/yii2/db/ActiveQuery.php(133): yii\db\Query->all(NULL)
#5 /var/www/humhub/protected/humhub/modules/content/migrations/m210211_051243_container_tag.php(67): yii\db\ActiveQuery->all()
#6 /var/www/humhub/protected/humhub/modules/content/migrations/m210211_051243_container_tag.php(37): m210211_051243_container_tag->moveContainerTags('humhub\\modules\\...')
#7 /var/www/humhub/protected/vendor/yiisoft/yii2/db/Migration.php(114): m210211_051243_container_tag->safeUp()
#8 /var/www/humhub/protected/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(744): yii\db\Migration->up()
#9 /var/www/humhub/protected/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(202): yii\console\controllers\BaseMigrateController->migrateUp('m210211_051243_...')
#10 [internal function]: yii\console\controllers\BaseMigrateController->actionUp(0)
#11 /var/www/humhub/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#12 /var/www/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams(Array)
#13 /var/www/humhub/protected/vendor/yiisoft/yii2/console/Controller.php(184): yii\base\Controller->runAction('up', Array)
#14 /var/www/humhub/protected/humhub/commands/MigrateController.php(198): yii\console\Controller->runAction('up')
#15 /var/www/humhub/protected/humhub/modules/admin/controllers/InformationController.php(95): humhub\commands\MigrateController::webMigrateAll()
#16 [internal function]: humhub\modules\admin\controllers\InformationController->actionDatabase()
#17 /var/www/humhub/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#18 /var/www/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams(Array)
#19 /var/www/humhub/protected/vendor/yiisoft/yii2/base/Module.php(534): yii\base\Controller->runAction('database', Array)
#20 /var/www/humhub/protected/vendor/yiisoft/yii2/web/Application.php(104): yii\base\Module->runAction('admin/informati...', Array)
#21 /var/www/humhub/protected/vendor/yiisoft/yii2/base/Application.php(392): yii\web\Application->handleRequest(Object(humhub\components\Request))
#22 /var/www/humhub/index.php(25): yii\base\Application->run()
#23 {main}
*** failed to apply m210211_051243_container_tag (time: 0.081s)


0 from 3 migrations were applied.

Migration failed. The rest of the migrations are canceled.`

**Comment by yurabakhtin** [comment]
@luke- PR https://github.com/humhub/humhub/pull/5248: I have implemented new methods in the core `\humhub\components\Migration` in order to run safe migrations when table, column or indexes already exist in DB, they all existing will be skipped like this:

<img width="1280" alt="fix_migration_container_tag" src="https://user-images.githubusercontent.com/6995524/129720323-1d1690d6-7eb0-4e6b-bb1e-38932a4dac81.png">

**Comment by Bust3r666** [comment]
Sorry, i din't understand to implement it.

I need to change \humhub\components\Migration.php code?

**Comment by luke-** [comment]
@yurabakhtin Thanks!

@Bust3r666 With 1.9.1 your issue should be solved.

**Comment by Bust011r** [comment]
Hi, I've updated to 1.9.1 and no have resolved my problem with database. I tried to do a test with test server with latest update and still not working.

What can i try to do to solve the problem?

The error is below attached:
``
Yii Migration Tool (based on Yii v2.0.40)

Total 5 new migrations to be applied:
	m210211_051243_container_tag
	m210331_115144_default_timezone
	m210506_060737_profile_field_directory_filter
	m210727_102150_follow_friend
	m210822_104736_mymodule_inital

*** applying m210211_051243_container_tag
    > skipped create table contentcontainer_tag, table does already exist ...
    > skipped create index unique-contentcontainer-tag in the table contentcontainer_tag, index already exists ...
    > skipped create table contentcontainer_tag_relation, table does already exist ...
    > skipped create primary index pk-contentcontainer-tag-rel in the table contentcontainer_tag_relation, primary index already exists ...
    > add foreign key fk-contentcontainer-tag-rel-contentcontainer-id: contentcontainer_tag_relation (contentcontainer_id) references contentcontainer (id) ...Exception: SQLSTATE[HY000]: General error: 1005 Can't create table `humhub_db`.`contentcontainer_tag_relation` (errno: 121 "Duplicate key on write or update")
The SQL being executed was: ALTER TABLE `contentcontainer_tag_relation` ADD CONSTRAINT `fk-contentcontainer-tag-rel-contentcontainer-id` FOREIGN KEY (`contentcontainer_id`) REFERENCES `contentcontainer` (`id`) ON DELETE CASCADE (/var/www/humhub/protected/vendor/yiisoft/yii2/db/Schema.php:678)
#0 /var/www/humhub/protected/vendor/yiisoft/yii2/db/Command.php(1304): yii\db\Schema->convertException(Object(PDOException), 'ALTER TABLE `co...')
#1 /var/www/humhub/protected/vendor/yiisoft/yii2/db/Command.php(1099): yii\db\Command->internalExecute('ALTER TABLE `co...')
#2 /var/www/humhub/protected/vendor/yiisoft/yii2/db/Migration.php(467): yii\db\Command->execute()
#3 /var/www/humhub/protected/humhub/components/Migration.php(218): yii\db\Migration->addForeignKey('fk-contentconta...', 'contentcontaine...', 'contentcontaine...', 'contentcontaine...', 'id', 'CASCADE', NULL)
#4 /var/www/humhub/protected/humhub/modules/content/migrations/m210211_051243_container_tag.php(32): humhub\components\Migration->safeAddForeignKey('fk-contentconta...', 'contentcontaine...', 'contentcontaine...', 'contentcontaine...', 'id', 'CASCADE')
#5 /var/www/humhub/protected/vendor/yiisoft/yii2/db/Migration.php(114): m210211_051243_container_tag->safeUp()
#6 /var/www/humhub/protected/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(744): yii\db\Migration->up()
#7 /var/www/humhub/protected/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(202): yii\console\controllers\BaseMigrateController->migrateUp('m210211_051243_...')
#8 [internal function]: yii\console\controllers\BaseMigrateController->actionUp(0)
#9 /var/www/humhub/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#10 /var/www/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams(Array)
#11 /var/www/humhub/protected/vendor/yiisoft/yii2/console/Controller.php(184): yii\base\Controller->runAction('up', Array)
#12 /var/www/humhub/protected/humhub/commands/MigrateController.php(198): yii\console\Controller->runAction('up')
#13 /var/www/humhub/protected/humhub/modules/admin/controllers/InformationController.php(95): humhub\commands\MigrateController::webMigrateAll()
#14 [internal function]: humhub\modules\admin\controllers\InformationController->actionDatabase()
#15 /var/www/humhub/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#16 /var/www/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams(Array)
#17 /var/www/humhub/protected/vendor/yiisoft/yii2/base/Module.php(534): yii\base\Controller->runAction('database', Array)
#18 /var/www/humhub/protected/vendor/yiisoft/yii2/web/Application.php(104): yii\base\Module->runAction('admin/informati...', Array)
#19 /var/www/humhub/protected/vendor/yiisoft/yii2/base/Application.php(392): yii\web\Application->handleRequest(Object(humhub\components\Request))
#20 /var/www/humhub/index.php(25): yii\base\Application->run()
#21 {main}
*** failed to apply m210211_051243_container_tag (time: 0.013s)


0 from 5 migrations were applied.

Migration failed. The rest of the migrations are canceled.
``

**Comment by luke-** [comment]
@Bust011r Can you try to update to 1.9.2?

**Comment by Bust011r** [comment]
Yes, i've updated without errors but the error with migration persist and there aren't error in db. 

`Yii Migration Tool (based on Yii v2.0.40)

Total 5 new migrations to be applied:
	m210211_051243_container_tag
	m210331_115144_default_timezone
	m210506_060737_profile_field_directory_filter
	m210727_102150_follow_friend
	m210822_104736_mymodule_inital

*** applying m210211_051243_container_tag
    > skipped create table contentcontainer_tag, table does already exist ...
    > skipped create index unique-contentcontainer-tag in the table contentcontainer_tag, index already exists ...
    > skipped create table contentcontainer_tag_relation, table does already exist ...
    > skipped create primary index pk-contentcontainer-tag-rel in the table contentcontainer_tag_relation, primary index already exists ...
    > add foreign key fk-contentcontainer-tag-rel-contentcontainer-id: contentcontainer_tag_relation (contentcontainer_id) references contentcontainer (id) ...Exception: SQLSTATE[HY000]: General error: 1005 Can't create table `humhub_db`.`contentcontainer_tag_relation` (errno: 121 "Duplicate key on write or update")
The SQL being executed was: ALTER TABLE `contentcontainer_tag_relation` ADD CONSTRAINT `fk-contentcontainer-tag-rel-contentcontainer-id` FOREIGN KEY (`contentcontainer_id`) REFERENCES `contentcontainer` (`id`) ON DELETE CASCADE (/var/www/humhub/protected/vendor/yiisoft/yii2/db/Schema.php:678)
#0 /var/www/humhub/protected/vendor/yiisoft/yii2/db/Command.php(1304): yii\db\Schema->convertException()
#1 /var/www/humhub/protected/vendor/yiisoft/yii2/db/Command.php(1099): yii\db\Command->internalExecute()
#2 /var/www/humhub/protected/vendor/yiisoft/yii2/db/Migration.php(467): yii\db\Command->execute()
#3 /var/www/humhub/protected/humhub/components/Migration.php(218): yii\db\Migration->addForeignKey()
#4 /var/www/humhub/protected/humhub/modules/content/migrations/m210211_051243_container_tag.php(32): humhub\components\Migration->safeAddForeignKey()
#5 /var/www/humhub/protected/vendor/yiisoft/yii2/db/Migration.php(114): m210211_051243_container_tag->safeUp()
#6 /var/www/humhub/protected/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(744): yii\db\Migration->up()
#7 /var/www/humhub/protected/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(202): yii\console\controllers\BaseMigrateController->migrateUp()
#8 [internal function]: yii\console\controllers\BaseMigrateController->actionUp()
#9 /var/www/humhub/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#10 /var/www/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams()
#11 /var/www/humhub/protected/vendor/yiisoft/yii2/console/Controller.php(184): yii\base\Controller->runAction()
#12 /var/www/humhub/protected/humhub/commands/MigrateController.php(198): yii\console\Controller->runAction()
#13 /var/www/humhub/protected/humhub/modules/admin/controllers/InformationController.php(95): humhub\commands\MigrateController::webMigrateAll()
#14 [internal function]: humhub\modules\admin\controllers\InformationController->actionDatabase()
#15 /var/www/humhub/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#16 /var/www/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams()
#17 /var/www/humhub/protected/vendor/yiisoft/yii2/base/Module.php(534): yii\base\Controller->runAction()
#18 /var/www/humhub/protected/vendor/yiisoft/yii2/web/Application.php(104): yii\base\Module->runAction()
#19 /var/www/humhub/protected/vendor/yiisoft/yii2/base/Application.php(392): yii\web\Application->handleRequest()
#20 /var/www/humhub/index.php(25): yii\base\Application->run()
#21 {main}
*** failed to apply m210211_051243_container_tag (time: 0.012s)


0 from 5 migrations were applied.

Migration failed. The rest of the migrations are canceled.
    `
